/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorActividades;
import java.text.DateFormat;
import Negocio.TablaConsulta;
import Negocio.TablaEscaneados;
/**
 *
 * @author User
 */
public class GuiConsultar extends javax.swing.JFrame {

    /**
     * Creates new form GuiConsultar
     */
    private Controlador.ControladorActividades contActi;
    
    
    public GuiConsultar() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        loadConbox();
        contActi =new ControladorActividades();
        btnFiltros.setVisible(false);
        JpanelFiltros.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrin = new javax.swing.JPanel();
        JdateFachaBusquda = new com.toedter.calendar.JDateChooser();
        jlFechaBus = new javax.swing.JLabel();
        JpanelFiltros = new javax.swing.JPanel();
        jbFiltro = new javax.swing.JLabel();
        jHoraInicio = new javax.swing.JLabel();
        jcomHoras = new javax.swing.JComboBox<>();
        Jlbhora = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnFiltros = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbActividades = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlFechaBus.setText("Fecha De Busqueda");

        JpanelFiltros.setBackground(new java.awt.Color(204, 204, 255));

        jbFiltro.setText("Filtros");

        javax.swing.GroupLayout JpanelFiltrosLayout = new javax.swing.GroupLayout(JpanelFiltros);
        JpanelFiltros.setLayout(JpanelFiltrosLayout);
        JpanelFiltrosLayout.setHorizontalGroup(
            JpanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelFiltrosLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jbFiltro)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        JpanelFiltrosLayout.setVerticalGroup(
            JpanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelFiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbFiltro)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        jHoraInicio.setText("Hora");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnFiltros.setText("Filtrar");
        btnFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrosActionPerformed(evt);
            }
        });

        tbActividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbActividades);

        javax.swing.GroupLayout jPanelPrinLayout = new javax.swing.GroupLayout(jPanelPrin);
        jPanelPrin.setLayout(jPanelPrinLayout);
        jPanelPrinLayout.setHorizontalGroup(
            jPanelPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrinLayout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addGroup(jPanelPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jHoraInicio)
                            .addComponent(jcomHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(JpanelFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelPrinLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanelPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlFechaBus, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(JdateFachaBusquda, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnFiltros)))))
                .addGroup(jPanelPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrinLayout.createSequentialGroup()
                        .addGroup(jPanelPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPrinLayout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(btnBuscar))
                            .addGroup(jPanelPrinLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(Jlbhora, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(206, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrinLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanelPrinLayout.setVerticalGroup(
            jPanelPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrinLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlFechaBus)
                    .addComponent(jHoraInicio)
                    .addComponent(btnBuscar))
                .addGap(2, 2, 2)
                .addGroup(jPanelPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JdateFachaBusquda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcomHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jlbhora, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanelPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrinLayout.createSequentialGroup()
                        .addComponent(btnFiltros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JpanelFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrinLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        DateFormat df= DateFormat.getDateInstance();
        if(JdateFachaBusquda.getDate()!=null){
        Jlbhora.setText(df.format(JdateFachaBusquda.getDate())+" "+(String)jcomHoras.getSelectedItem());
        contActi.consultarActividades(df.format(JdateFachaBusquda.getDate())+" "+(String)jcomHoras.getSelectedItem());
        loadTabla();
        btnFiltros.setVisible(true);
        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrosActionPerformed
        // TODO add your handling code here:
        JpanelFiltros.setVisible(true);
    }//GEN-LAST:event_btnFiltrosActionPerformed

  
public void loadConbox(){
String [] Horas={"00:00:00.0","01:00:00.0","02:00:00.0","03:00:00.0","04:00:00.0",
                "05:00:00.0","06:00:00.0","07:00:00.0","08:00:00.0","09:00:00.0","10:00:00.0","11:00:00.0","12:00:00.0","13:00:00.0",
                "14:00:00.0","15:00:00.0","16:00:00.0","17:00:00.0","18:00:00.0","19:00:00.0","20:00:00.0","21:00:00.0","22:00:00.0","23:00:00.0","24:00:00.0"} ;
for(int i =0; i <Horas.length;i++){
       jcomHoras.addItem(Horas[i]);
       }

}

public void loadTabla(){
    Negocio.TablaConsulta tc=new Negocio.TablaConsulta(contActi.getActividades());
    tbActividades.setModel(tc);
}
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JdateFachaBusquda;
    private javax.swing.JLabel Jlbhora;
    private javax.swing.JPanel JpanelFiltros;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnFiltros;
    private javax.swing.JLabel jHoraInicio;
    private javax.swing.JPanel jPanelPrin;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jbFiltro;
    private javax.swing.JComboBox<String> jcomHoras;
    private javax.swing.JLabel jlFechaBus;
    private javax.swing.JTable tbActividades;
    // End of variables declaration//GEN-END:variables
}
