/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.text.DateFormat;

/**
 *
 * @author User
 */
public class GuiConsultar extends javax.swing.JFrame {

    /**
     * Creates new form GuiConsultar
     */
    public GuiConsultar() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        loadConbox();
        btnFiltros.setVisible(false);
        JpanelFiltros.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrin = new javax.swing.JPanel();
        JdateFachaBusquda = new com.toedter.calendar.JDateChooser();
        jlFechaBus = new javax.swing.JLabel();
        JpanelFiltros = new javax.swing.JPanel();
        jbFiltro = new javax.swing.JLabel();
        jHoraInicio = new javax.swing.JLabel();
        jcomHoras = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        JbAm_pm = new javax.swing.JComboBox<>();
        Jlbhora = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnFiltros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlFechaBus.setText("Fecha De Busqueda");

        JpanelFiltros.setBackground(new java.awt.Color(204, 204, 255));

        jbFiltro.setText("Filtros");

        javax.swing.GroupLayout JpanelFiltrosLayout = new javax.swing.GroupLayout(JpanelFiltros);
        JpanelFiltros.setLayout(JpanelFiltrosLayout);
        JpanelFiltrosLayout.setHorizontalGroup(
            JpanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelFiltrosLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jbFiltro)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        JpanelFiltrosLayout.setVerticalGroup(
            JpanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelFiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbFiltro)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        jHoraInicio.setText("Hora");

        jLabel1.setText("AM/PM");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnFiltros.setText("Filtrar");
        btnFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPrinLayout = new javax.swing.GroupLayout(jPanelPrin);
        jPanelPrin.setLayout(jPanelPrinLayout);
        jPanelPrinLayout.setHorizontalGroup(
            jPanelPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrinLayout.createSequentialGroup()
                .addGroup(jPanelPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrinLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPrinLayout.createSequentialGroup()
                                .addComponent(jlFechaBus, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addGroup(jPanelPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jHoraInicio)
                                    .addComponent(jcomHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)
                                .addGroup(jPanelPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelPrinLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(65, 65, 65)
                                        .addComponent(btnBuscar))
                                    .addGroup(jPanelPrinLayout.createSequentialGroup()
                                        .addComponent(JbAm_pm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Jlbhora, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(JdateFachaBusquda, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JpanelFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelPrinLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(btnFiltros)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanelPrinLayout.setVerticalGroup(
            jPanelPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrinLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlFechaBus)
                    .addComponent(jHoraInicio)
                    .addComponent(jLabel1)
                    .addComponent(btnBuscar))
                .addGap(2, 2, 2)
                .addGroup(jPanelPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JdateFachaBusquda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcomHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JbAm_pm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Jlbhora, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(btnFiltros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JpanelFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        DateFormat df= DateFormat.getDateInstance();
        if(JdateFachaBusquda.getDate()!=null){
        Jlbhora.setText(df.format(JdateFachaBusquda.getDate())+" "+(String)jcomHoras.getSelectedItem()+" "+(String)JbAm_pm.getSelectedItem());
        btnFiltros.setVisible(true);
        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrosActionPerformed
        // TODO add your handling code here:
        JpanelFiltros.setVisible(true);
    }//GEN-LAST:event_btnFiltrosActionPerformed

  
public void loadConbox(){
String [] Horas={"00:00:00","01:00:00","02:00:00","03:00:00","04:00:00",
                "05:00:00","06:00:00","07:00:00","08:00:00","09:00:00","10:00:00","11:00:00","12:00:00"} ;
String[] AM_PM={"AM","PM"};
for(int i =0; i <Horas.length;i++){
       jcomHoras.addItem(Horas[i]);
       }
for(int i =0; i <AM_PM.length;i++){
       JbAm_pm.addItem(AM_PM[i]);
       }

}
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JbAm_pm;
    private com.toedter.calendar.JDateChooser JdateFachaBusquda;
    private javax.swing.JLabel Jlbhora;
    private javax.swing.JPanel JpanelFiltros;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnFiltros;
    private javax.swing.JLabel jHoraInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelPrin;
    private javax.swing.JLabel jbFiltro;
    private javax.swing.JComboBox<String> jcomHoras;
    private javax.swing.JLabel jlFechaBus;
    // End of variables declaration//GEN-END:variables
}
